### ISSUE TITLE
install script does not check for wget.

### ISSUE THREAD

**Issue by Timo-EickGit** [swiftwave-org/installer#1]
initialy opened https://github.com/swiftwave-org/swiftwave/issues/8 
was then pointed here to open by @tanmoysrt 

script does not check for wget when installing. resulting in the script not finding files

fix would be to simply do the same as for unzip 

# Check for `wget` command 
```bash
if ! command -v wget &> /dev/null then 
  echo "wget command could not be found"  
  echo "Installing wget..." 
  sudo apt update -y 
  sudo apt install -y wget
 fi
```

**Comment by tanmoysrt** [comment]
@Timo-EickGit do you like to add this part in script ?

**Comment by Timo-EickGit** [comment]
im not familiar on how to do it so it would be easier for you to just do it

**Comment by tanmoysrt** [comment]
> im not familiar on how to do it so it would be easier for you to just do it

Ok no issue ! Thanks for opening issue

**Comment by tanmoysrt** [comment]
Fixed in latest  commit :rocket:
