### ISSUE TITLE
setup.sh errors out with "services.app.ports.0 must be a string or number"

### ISSUE THREAD

**Issue by Timo-EickGit** [swiftwave-org/installer#2]
OS: Debian 12

After confirming public IP the setup.sh exits with error "services.app.ports.0 must be a string or number"

**Comment by Timo-EickGit** [comment]
what os / dist was the install script tested on?

**Comment by tanmoysrt** [comment]
@Timo-EickGit We have tested specially in ubuntu 
I think the problem is with docker compose, the port environment variable not set properly.
If you can provide a detailed info that will be great !

**Comment by tanmoysrt** [comment]
I found the issue.It's a bug of docker stack version 3.1 . I will update to 3.5 which will resolve the issue. 
Thanks for reporting @Timo-EickGit

**Comment by tanmoysrt** [comment]
Fixed :rocket:
